name: picogram
description: A full stack clone of Instagram

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.9
  firebase_storage: ^10.2.9
  image_picker: ^0.8.4+11
  provider: ^6.0.2
  uuid: ^3.0.6
  google_fonts: ^2.3.1
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - google_fonts/

